version: '3.8'

services:
  api:
    image: sample-cleanarchitecture-cqrs.api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Production  
