@rootUrl=https://localhost:7010

POST {{rootUrl}}/api/v1/users/register
Content-Type: application/json

{
    "username": "ZenMaxe",
    "email": "test@gmail.com",
    "password": "55555eeeeAbbbb@",
    "firstname": "Hossein",
    "lastname": "Sanjabian"
}


